/* ============================================================
   EXAMALLOCATE DB — NPTEL-STYLE EXAMINATION PORTAL
   MySQL 8.0+

   IMPORTANT DESIGN CHANGE
   -----------------------
   The candidate does NOT enter:
     - application number
     - registration number
     - session ID
     - exam date
     - exam time

   The portal generates the application number after registration
   and assigns the examination session automatically.

   This is ONE MySQL script. No separate database folder is needed.
   ============================================================ */

DROP DATABASE IF EXISTS ExamAllocateDB;
CREATE DATABASE ExamAllocateDB
    CHARACTER SET utf8mb4
    COLLATE utf8mb4_unicode_ci;

USE ExamAllocateDB;


/* ============================================================
   1. COURSE MASTER
   Used as the course catalogue for the NPTEL-style frontend.
   ============================================================ */

CREATE TABLE course (
    course_id BIGINT PRIMARY KEY AUTO_INCREMENT,
    course_code VARCHAR(50) NOT NULL UNIQUE,
    course_name VARCHAR(200) NOT NULL UNIQUE,
    instructor VARCHAR(200),
    institute VARCHAR(200),
    duration_weeks INT,
    category VARCHAR(100),
    level VARCHAR(50),
    credits INT,
    course_url VARCHAR(500),
    status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE'
);


/* ============================================================
   2. STUDENT / CANDIDATE
   Application number is SYSTEM GENERATED by Spring Boot.
   Candidate never enters it during new registration.
   ============================================================ */

CREATE TABLE student (
    student_id BIGINT PRIMARY KEY AUTO_INCREMENT,

    application_no VARCHAR(50) NOT NULL UNIQUE,

    name VARCHAR(150) NOT NULL,

    dob DATE NOT NULL,

    gender VARCHAR(30) NOT NULL,

    category VARCHAR(30) NOT NULL,

    phone VARCHAR(20) NOT NULL,

    email VARCHAR(150) NOT NULL,

    address VARCHAR(255) NOT NULL,

    city VARCHAR(100),

    state VARCHAR(100) NOT NULL,

    pincode VARCHAR(10) NOT NULL,

    preferred_city_1 VARCHAR(100) NOT NULL,

    preferred_city_2 VARCHAR(100),

    school_name VARCHAR(150) NOT NULL,

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    INDEX idx_student_email (email),
    INDEX idx_student_city1 (preferred_city_1)
);


/* ============================================================
   3. EXAM CENTRE
   ============================================================ */

CREATE TABLE exam_center (
    center_id BIGINT PRIMARY KEY AUTO_INCREMENT,

    center_name VARCHAR(200) NOT NULL,

    city VARCHAR(100) NOT NULL,

    address VARCHAR(500),

    total_capacity INT NOT NULL DEFAULT 0,

    status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',

    INDEX idx_center_city (city)
);


/* ============================================================
   4. ROOM
   ============================================================ */

CREATE TABLE room (
    room_id BIGINT PRIMARY KEY AUTO_INCREMENT,

    center_id BIGINT NOT NULL,

    room_number VARCHAR(50) NOT NULL,

    capacity INT NOT NULL,

    floor INT,

    status VARCHAR(30) NOT NULL DEFAULT 'AVAILABLE',

    CONSTRAINT fk_room_center
        FOREIGN KEY (center_id)
        REFERENCES exam_center(center_id)
        ON DELETE CASCADE,

    CONSTRAINT uq_room_center
        UNIQUE (center_id, room_number)
);


/* ============================================================
   5. EXAM SESSION
   The candidate selects only the COURSE.
   Session/date/shift are assigned by the system.
   ============================================================ */

CREATE TABLE exam_session (
    session_id BIGINT PRIMARY KEY AUTO_INCREMENT,

    exam_name VARCHAR(200) NOT NULL,

    exam_date DATE NOT NULL,

    shift_name VARCHAR(100) NOT NULL,

    start_time TIME NOT NULL,

    end_time TIME NOT NULL,

    status VARCHAR(30) NOT NULL DEFAULT 'SCHEDULED',

    INDEX idx_session_course_date (exam_name, exam_date, start_time)
);


/* ============================================================
   6. REGISTRATION
   No application number is stored here because it belongs to
   STUDENT. The application number is the candidate's portal
   identifier and is generated by the backend.

   session_id is assigned by the backend.
   ============================================================ */

CREATE TABLE registration (
    reg_id BIGINT PRIMARY KEY AUTO_INCREMENT,

    student_id BIGINT NOT NULL,

    session_id BIGINT NOT NULL,

    reg_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_registration_student
        FOREIGN KEY (student_id)
        REFERENCES student(student_id)
        ON DELETE CASCADE,

    CONSTRAINT fk_registration_session
        FOREIGN KEY (session_id)
        REFERENCES exam_session(session_id),

    CONSTRAINT uq_student_session
        UNIQUE (student_id, session_id),

    INDEX idx_registration_session (session_id)
);


/* ============================================================
   7. SPECIAL NEEDS / ACCESSIBILITY REQUEST
   ============================================================ */

CREATE TABLE special_needs_request (
    request_id BIGINT PRIMARY KEY AUTO_INCREMENT,

    student_id BIGINT NOT NULL,

    accommodation_type VARCHAR(150) NOT NULL,

    approved_status VARCHAR(30) NOT NULL DEFAULT 'PENDING',

    CONSTRAINT fk_special_student
        FOREIGN KEY (student_id)
        REFERENCES student(student_id)
        ON DELETE CASCADE,

    INDEX idx_special_status (approved_status)
);


/* ============================================================
   8. SEAT ALLOCATION
   One registration can receive one seat.
   ============================================================ */

CREATE TABLE seat_allocation (
    allocation_id BIGINT PRIMARY KEY AUTO_INCREMENT,

    reg_id BIGINT NOT NULL,

    center_id BIGINT NOT NULL,

    room_id BIGINT NOT NULL,

    seat_number INT NOT NULL,

    version BIGINT NOT NULL DEFAULT 0,

    allocated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_allocation_registration
        FOREIGN KEY (reg_id)
        REFERENCES registration(reg_id)
        ON DELETE CASCADE,

    CONSTRAINT fk_allocation_center
        FOREIGN KEY (center_id)
        REFERENCES exam_center(center_id),

    CONSTRAINT fk_allocation_room
        FOREIGN KEY (room_id)
        REFERENCES room(room_id),

    CONSTRAINT uq_registration_allocation
        UNIQUE (reg_id),

    CONSTRAINT uq_room_seat_registration
        UNIQUE (room_id, seat_number, reg_id),

    INDEX idx_allocation_room (room_id)
);


/* ============================================================
   9. ALLOCATION LOG
   Keeps the reason for every allocation/fallback decision.
   ============================================================ */

CREATE TABLE allocation_log (
    log_id BIGINT PRIMARY KEY AUTO_INCREMENT,

    reg_id BIGINT NOT NULL,

    center_id BIGINT NULL,

    reason VARCHAR(500) NOT NULL,

    logged_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_log_registration
        FOREIGN KEY (reg_id)
        REFERENCES registration(reg_id)
        ON DELETE CASCADE,

    CONSTRAINT fk_log_center
        FOREIGN KEY (center_id)
        REFERENCES exam_center(center_id)
        ON DELETE SET NULL,

    INDEX idx_log_registration (reg_id)
);


/* ============================================================
   10. ADMIT CARD / HALL TICKET
   Generated only after seat allocation.
   ============================================================ */

CREATE TABLE admit_card (
    admit_card_id BIGINT PRIMARY KEY AUTO_INCREMENT,

    reg_id BIGINT NOT NULL UNIQUE,

    hall_ticket_no VARCHAR(100) NOT NULL UNIQUE,

    issue_date DATE NOT NULL,

    download_count INT NOT NULL DEFAULT 0,

    CONSTRAINT fk_admit_registration
        FOREIGN KEY (reg_id)
        REFERENCES registration(reg_id)
        ON DELETE CASCADE
);


/* ============================================================
   11. GRIEVANCE
   ============================================================ */

CREATE TABLE grievance (
    grievance_id BIGINT PRIMARY KEY AUTO_INCREMENT,

    reg_id BIGINT NOT NULL,

    description VARCHAR(1000) NOT NULL,

    filed_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

    status VARCHAR(30) NOT NULL DEFAULT 'OPEN',

    resolution VARCHAR(1000),

    CONSTRAINT fk_grievance_registration
        FOREIGN KEY (reg_id)
        REFERENCES registration(reg_id)
        ON DELETE CASCADE,

    INDEX idx_grievance_registration (reg_id),
    INDEX idx_grievance_status (status)
);


/* ============================================================
   12. OCCUPANCY
   Internal helper table used for safe concurrent allocation.
   One row represents one room for one examination session.
   ============================================================ */

CREATE TABLE room_occupancy (
    session_id BIGINT NOT NULL,

    room_id BIGINT NOT NULL,

    occupied INT NOT NULL DEFAULT 0,

    PRIMARY KEY (session_id, room_id),

    CONSTRAINT fk_occupancy_session
        FOREIGN KEY (session_id)
        REFERENCES exam_session(session_id)
        ON DELETE CASCADE,

    CONSTRAINT fk_occupancy_room
        FOREIGN KEY (room_id)
        REFERENCES room(room_id)
        ON DELETE CASCADE
);


/* ============================================================
   13. INVIGILATOR
   ============================================================ */

CREATE TABLE invigilator (
    invigilator_id BIGINT PRIMARY KEY AUTO_INCREMENT,

    employee_code VARCHAR(50) NOT NULL UNIQUE,

    first_name VARCHAR(100) NOT NULL,

    last_name VARCHAR(100) NOT NULL,

    email VARCHAR(150) NOT NULL UNIQUE,

    phone VARCHAR(20),

    department VARCHAR(100),

    status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE'
);


/* ============================================================
   14. INVIGILATOR ASSIGNMENT
   ============================================================ */

CREATE TABLE invigilator_assignment (
    assignment_id BIGINT PRIMARY KEY AUTO_INCREMENT,

    room_id BIGINT NOT NULL,

    session_id BIGINT NOT NULL,

    invigilator_id BIGINT NOT NULL,

    assignment_role VARCHAR(50) NOT NULL DEFAULT 'INVIGILATOR',

    assigned_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_assignment_room
        FOREIGN KEY (room_id)
        REFERENCES room(room_id)
        ON DELETE CASCADE,

    CONSTRAINT fk_assignment_session
        FOREIGN KEY (session_id)
        REFERENCES exam_session(session_id)
        ON DELETE CASCADE,

    CONSTRAINT fk_assignment_invigilator
        FOREIGN KEY (invigilator_id)
        REFERENCES invigilator(invigilator_id)
        ON DELETE CASCADE,

    CONSTRAINT uq_room_session_invigilator
        UNIQUE(room_id, session_id, invigilator_id)
);


/* ============================================================
   15. NPTEL COURSE DATA
   ============================================================ */

INSERT INTO course
(course_code, course_name, instructor, institute, duration_weeks,
 category, level, credits, course_url)
VALUES
('NPTEL-CS01','Programming in Java','NPTEL Faculty','IIT Kharagpur',12,'Computer Science','Beginner',3,'https://nptel.ac.in'),
('NPTEL-CS02','Data Structures and Algorithms','NPTEL Faculty','IIT Madras',12,'Computer Science','Intermediate',3,'https://nptel.ac.in'),
('NPTEL-CS03','Database Management Systems','NPTEL Faculty','IIT Kharagpur',12,'Computer Science','Intermediate',3,'https://nptel.ac.in'),
('NPTEL-CS04','Computer Networks','NPTEL Faculty','IIT Madras',12,'Computer Science','Intermediate',3,'https://nptel.ac.in'),
('NPTEL-CS05','Operating Systems','NPTEL Faculty','IIT Madras',12,'Computer Science','Intermediate',3,'https://nptel.ac.in'),
('NPTEL-AI01','Introduction to Machine Learning','NPTEL Faculty','IIT Madras',12,'Artificial Intelligence','Intermediate',3,'https://nptel.ac.in'),
('NPTEL-AI02','Deep Learning','NPTEL Faculty','IIT Madras',12,'Artificial Intelligence','Advanced',3,'https://nptel.ac.in'),
('NPTEL-AI03','Artificial Intelligence: Search Methods for Problem Solving','NPTEL Faculty','IIT Kharagpur',12,'Artificial Intelligence','Advanced',3,'https://nptel.ac.in'),
('NPTEL-AI04','Reinforcement Learning','NPTEL Faculty','IIT Madras',12,'Artificial Intelligence','Advanced',3,'https://nptel.ac.in'),
('NPTEL-AI05','Natural Language Processing','NPTEL Faculty','IIT Kharagpur',12,'Artificial Intelligence','Advanced',3,'https://nptel.ac.in'),
('NPTEL-DS01','Data Science for Engineers','NPTEL Faculty','IIT Madras',12,'Data Science','Beginner',3,'https://nptel.ac.in'),
('NPTEL-DS02','Data Analytics with Python','NPTEL Faculty','IIT Roorkee',12,'Data Science','Intermediate',3,'https://nptel.ac.in'),
('NPTEL-EC01','Digital Circuits','NPTEL Faculty','IIT Kharagpur',12,'Electronics','Intermediate',3,'https://nptel.ac.in'),
('NPTEL-EC02','Embedded Systems','NPTEL Faculty','IIT Madras',12,'Electronics','Intermediate',3,'https://nptel.ac.in'),
('NPTEL-MA01','Probability and Statistics','NPTEL Faculty','IIT Kanpur',12,'Mathematics','Beginner',3,'https://nptel.ac.in');


/* ============================================================
   16. EXAM SESSIONS
   These are available to the portal.
   Candidate selects ONLY the course.
   The backend picks the earliest scheduled session.
   ============================================================ */

INSERT INTO exam_session
(exam_name, exam_date, shift_name, start_time, end_time, status)
VALUES
('Programming in Java','2026-11-07','Morning','09:00:00','12:00:00','SCHEDULED'),
('Programming in Java','2026-11-07','Afternoon','14:00:00','17:00:00','SCHEDULED'),

('Data Structures and Algorithms','2026-11-08','Morning','09:00:00','12:00:00','SCHEDULED'),
('Data Structures and Algorithms','2026-11-08','Afternoon','14:00:00','17:00:00','SCHEDULED'),

('Database Management Systems','2026-11-14','Morning','09:00:00','12:00:00','SCHEDULED'),
('Database Management Systems','2026-11-14','Afternoon','14:00:00','17:00:00','SCHEDULED'),

('Computer Networks','2026-11-15','Morning','09:00:00','12:00:00','SCHEDULED'),
('Operating Systems','2026-11-21','Morning','09:00:00','12:00:00','SCHEDULED'),

('Introduction to Machine Learning','2026-11-22','Morning','09:00:00','12:00:00','SCHEDULED'),
('Deep Learning','2026-11-28','Morning','09:00:00','12:00:00','SCHEDULED'),

('Artificial Intelligence: Search Methods for Problem Solving','2026-11-29','Morning','09:00:00','12:00:00','SCHEDULED'),
('Reinforcement Learning','2026-12-05','Morning','09:00:00','12:00:00','SCHEDULED'),

('Natural Language Processing','2026-12-06','Morning','09:00:00','12:00:00','SCHEDULED'),
('Data Science for Engineers','2026-12-12','Morning','09:00:00','12:00:00','SCHEDULED'),
('Data Analytics with Python','2026-12-13','Morning','09:00:00','12:00:00','SCHEDULED'),
('Digital Circuits','2026-12-19','Morning','09:00:00','12:00:00','SCHEDULED'),
('Embedded Systems','2026-12-20','Morning','09:00:00','12:00:00','SCHEDULED'),
('Probability and Statistics','2026-12-26','Morning','09:00:00','12:00:00','SCHEDULED');


/* ============================================================
   17. EXAM CENTRES
   ============================================================ */

INSERT INTO exam_center
(center_name, city, address, total_capacity)
VALUES
('NPTEL Examination Centre - Pune','Pune','Cummins College Road, Pune, Maharashtra',200),
('NPTEL Examination Centre - Mumbai','Mumbai','Andheri East, Mumbai, Maharashtra',200),
('NPTEL Examination Centre - Nagpur','Nagpur','Central Nagpur, Maharashtra',150),
('NPTEL Examination Centre - Bengaluru','Bengaluru','Electronic City, Bengaluru, Karnataka',250),
('NPTEL Examination Centre - Hyderabad','Hyderabad','HITEC City, Hyderabad, Telangana',200),
('NPTEL Examination Centre - Delhi','Delhi','New Delhi, Delhi',250);


/* ============================================================
   18. ROOMS
   Ten rooms per major centre.
   ============================================================ */

INSERT INTO room (center_id, room_number, capacity, floor)
VALUES
(1,'P-101',25,1),(1,'P-102',25,1),(1,'P-103',25,1),(1,'P-104',25,1),
(1,'P-201',25,2),(1,'P-202',25,2),(1,'P-203',25,2),(1,'P-204',25,2),

(2,'M-101',25,1),(2,'M-102',25,1),(2,'M-103',25,1),(2,'M-104',25,1),
(2,'M-201',25,2),(2,'M-202',25,2),(2,'M-203',25,2),(2,'M-204',25,2),

(3,'N-101',25,1),(3,'N-102',25,1),(3,'N-103',25,1),(3,'N-104',25,1),
(3,'N-201',25,2),(3,'N-202',25,2),

(4,'B-101',25,1),(4,'B-102',25,1),(4,'B-103',25,1),(4,'B-104',25,1),
(4,'B-201',25,2),(4,'B-202',25,2),(4,'B-203',25,2),(4,'B-204',25,2),
(4,'B-301',25,3),(4,'B-302',25,3),

(5,'H-101',25,1),(5,'H-102',25,1),(5,'H-103',25,1),(5,'H-104',25,1),
(5,'H-201',25,2),(5,'H-202',25,2),(5,'H-203',25,2),(5,'H-204',25,2),

(6,'D-101',25,1),(6,'D-102',25,1),(6,'D-103',25,1),(6,'D-104',25,1),
(6,'D-201',25,2),(6,'D-202',25,2),(6,'D-203',25,2),(6,'D-204',25,2);


/* ============================================================
   19. INVIGILATORS
   ============================================================ */

INSERT INTO invigilator
(employee_code, first_name, last_name, email, phone, department)
VALUES
('INV001','Amit','Sharma','inv001@nptel-demo.local','9000000001','Computer Science'),
('INV002','Neha','Patil','inv002@nptel-demo.local','9000000002','Electronics'),
('INV003','Rahul','Mehta','inv003@nptel-demo.local','9000000003','Computer Science'),
('INV004','Priya','Kulkarni','inv004@nptel-demo.local','9000000004','Administration'),
('INV005','Rohit','Deshmukh','inv005@nptel-demo.local','9000000005','Computer Science'),
('INV006','Sneha','Joshi','inv006@nptel-demo.local','9000000006','Administration'),
('INV007','Karan','Shah','inv007@nptel-demo.local','9000000007','Electronics'),
('INV008','Pooja','Nair','inv008@nptel-demo.local','9000000008','Computer Science');


/* ============================================================
   20. INITIAL ROOM-SESSION OCCUPANCY
   Empty at zero. AllocationService increases this atomically.
   ============================================================ */

INSERT INTO room_occupancy (session_id, room_id, occupied)
SELECT es.session_id, r.room_id, 0
FROM exam_session es
CROSS JOIN room r;


/* ============================================================
   21. USEFUL VIEWS
   These do not create a separate database/folder.
   They are simply reusable MySQL queries.
   ============================================================ */

CREATE OR REPLACE VIEW v_exam_sessions AS
SELECT
    es.session_id,
    es.exam_name,
    es.exam_date,
    es.shift_name,
    es.start_time,
    es.end_time,
    es.status
FROM exam_session es
ORDER BY es.exam_date, es.start_time;


CREATE OR REPLACE VIEW v_registration_status AS
SELECT
    r.reg_id,
    s.application_no,
    s.name AS candidate_name,
    s.email,
    es.exam_name,
    es.exam_date,
    es.shift_name,
    es.start_time,
    es.end_time,
    r.reg_date,
    CASE
        WHEN sa.allocation_id IS NULL THEN 'REGISTERED'
        ELSE 'SEAT_ALLOCATED'
    END AS registration_status,
    ec.center_name,
    ec.city,
    ro.room_number,
    ro.floor,
    sa.seat_number
FROM registration r
JOIN student s
    ON s.student_id = r.student_id
JOIN exam_session es
    ON es.session_id = r.session_id
LEFT JOIN seat_allocation sa
    ON sa.reg_id = r.reg_id
LEFT JOIN exam_center ec
    ON ec.center_id = sa.center_id
LEFT JOIN room ro
    ON ro.room_id = sa.room_id;


/* ============================================================
   22. TEST / VERIFICATION QUERIES
   At this point candidate-dependent tables are intentionally
   EMPTY. Candidates are created by the frontend.
   ============================================================ */

SELECT 'Courses' AS item, COUNT(*) AS total FROM course
UNION ALL
SELECT 'Exam Sessions', COUNT(*) FROM exam_session
UNION ALL
SELECT 'Exam Centres', COUNT(*) FROM exam_center
UNION ALL
SELECT 'Rooms', COUNT(*) FROM room
UNION ALL
SELECT 'Invigilators', COUNT(*) FROM invigilator
UNION ALL
SELECT 'Candidates', COUNT(*) FROM student
UNION ALL
SELECT 'Registrations', COUNT(*) FROM registration
UNION ALL
SELECT 'Seat Allocations', COUNT(*) FROM seat_allocation
UNION ALL
SELECT 'Admit Cards', COUNT(*) FROM admit_card
UNION ALL
SELECT 'Grievances', COUNT(*) FROM grievance;


/* ============================================================
   23. OPTIONAL DEMO QUERIES
   Uncomment when you want to inspect data in Workbench.

   SELECT * FROM course;
   SELECT * FROM exam_session ORDER BY exam_date, start_time;
   SELECT * FROM exam_center;
   SELECT * FROM room;
   SELECT * FROM v_registration_status;
   ============================================================ */


/* ============================================================
   END OF NPTEL-STYLE EXAMALLOCATE DATABASE
   ============================================================ */
