package com.examallocate.service;

import com.examallocate.dto.*;
import com.examallocate.entity.*;
import com.examallocate.repository.*;
import lombok.RequiredArgsConstructor;
import org.springframework.http.HttpStatus;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.web.server.ResponseStatusException;

import java.time.LocalDateTime;
import java.time.Year;
import java.util.Locale;
import java.util.UUID;

@Service
@RequiredArgsConstructor
public class RegistrationService {
    private final StudentRepository studentRepository;
    private final ExamSessionRepository sessionRepository;
    private final RegistrationRepository registrationRepository;
    private final SpecialNeedsRequestRepository specialNeedsRepository;

    /**
     * Candidate supplies course, identity/contact details and city preferences.
     * Application number and exam session are generated/assigned by the portal.
     */
    @Transactional
    public ApplyResponse apply(ApplyRequest req) {
        String course = req.courseName().trim();

        ExamSession session = sessionRepository.findFirstByExamNameOrderByExamDateAscStartTimeAsc(course)
                .orElseThrow(() -> new ResponseStatusException(
                        HttpStatus.NOT_FOUND, "The selected course is not available for exam registration"));

        String appNo = generateApplicationNo();

        Student student = new Student();
        student.setApplicationNo(appNo);
        student.setName(req.name().trim());
        student.setDob(req.dob());
        student.setGender(req.gender().trim());
        student.setCategory(req.category().trim());
        student.setPhone(req.phone().trim());
        student.setEmail(req.email().trim().toLowerCase(Locale.ROOT));
        student.setAddress(req.address().trim());
        student.setCity(req.city().trim());
        student.setState(req.state().trim());
        student.setPincode(req.pincode().trim());
        student.setSchoolName(req.schoolName().trim());
        student.setPreferredCity1(req.preferredCity1().trim());
        student.setPreferredCity2(req.preferredCity2() == null || req.preferredCity2().isBlank()
                ? null : req.preferredCity2().trim());

        student = studentRepository.save(student);

        Registration reg = new Registration();
        reg.setStudent(student);
        reg.setSession(session);
        reg.setRegDate(LocalDateTime.now());
        reg = registrationRepository.save(reg);

        if (req.accommodationType() != null && !req.accommodationType().isBlank()) {
            SpecialNeedsRequest sn = new SpecialNeedsRequest();
            sn.setStudent(student);
            sn.setAccommodationType(req.accommodationType().trim());
            sn.setApprovedStatus("PENDING");
            specialNeedsRepository.save(sn);
        }

        return new ApplyResponse(
                reg.getRegId(),
                student.getStudentId(),
                appNo,
                session.getExamName(),
                session.getExamDate(),
                session.getShiftName(),
                session.getStartTime(),
                session.getEndTime(),
                "Registration successful. Your application number has been generated by the portal.");
    }

    private String generateApplicationNo() {
        String app;
        do {
            app = "NPTEL" + Year.now().getValue() + "-" +
                    UUID.randomUUID().toString().replace("-", "").substring(0, 8).toUpperCase(Locale.ROOT);
        } while (studentRepository.findByApplicationNo(app).isPresent());
        return app;
    }

    @Transactional(readOnly = true)
    public RegistrationLookupResponse lookup(String applicationNo, String email) {
        Registration r = registrationRepository
                .findFirstByStudent_ApplicationNoAndStudent_EmailIgnoreCase(
                        applicationNo.trim(), email.trim())
                .orElseThrow(() -> new ResponseStatusException(
                        HttpStatus.NOT_FOUND, "No registration found for the application number and email"));

        ExamSession s = r.getSession();
        return new RegistrationLookupResponse(
                r.getRegId(),
                r.getStudent().getApplicationNo(),
                r.getStudent().getName(),
                s.getExamName(),
                s.getExamDate(),
                s.getShiftName(),
                s.getStartTime(),
                s.getEndTime());
    }

    @Transactional(readOnly = true)
    public Registration requireOwned(Long regId, String applicationNo) {
        Registration r = registrationRepository.findById(regId).orElse(null);
        if (r == null || applicationNo == null ||
                !r.getStudent().getApplicationNo().equals(applicationNo.trim()))
            throw new ResponseStatusException(
                    HttpStatus.NOT_FOUND, "No registration matches that application number");
        return r;
    }
}
